name: build_image

on:
  push:
    branches:
      - 'master'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
#  # 新增：前端构建工作
#  build-frontend:
#    runs-on: ubuntu-latest
#    outputs:
#      frontend-artifact: ${{ steps.upload-frontend.outputs.artifact-name }}
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Setup Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: '20'
#          cache: 'npm'
#          cache-dependency-path: src-web/package-lock.json
#
#      - name: Install dependencies
#        run: |
#          cd src-web
#          npm ci
#
#      - name: Build frontend
#        run: |
#          cd src-web
#          npm run build
#
#      - name: Upload frontend build
#        uses: actions/upload-artifact@v4
#        id: upload-frontend
#        with:
#          name: frontend-build-${{ github.sha }}
#          path: src-web/dist/
#          retention-days: 7
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

#      - name: Download frontend build
#        uses: actions/download-artifact@v4
#        with:
#          name: frontend-build-${{ github.sha }}
#          path: web/dist

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Registry
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          #password: ${{ secrets.GITHUB_TOKEN }}
          password: ${{ secrets.GIT_TOKEN }}

      # gammu-web metadata
      - name: Extract metadata for gammu-web
        id: meta_gammu
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/gammu-web
          tags: |
            type=ref,event=branch
            type=sha
            type=ref,event=tag
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}

      - name: 编译 gammu-web 镜像
        uses: docker/build-push-action@v5
        with:
          context: .
#          file: actions.Dockerfile
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_gammu.outputs.tags }}
          labels: ${{ steps.meta_gammu.outputs.labels }}
          platforms: linux/amd64,linux/arm64